### ISSUE TITLE
certificate for cdn.predix-ui.com is about to expire

### ISSUE THREAD

**Issue by ed-the-cat** [predix-ui/px-cdn.github.io#1]
The security certificate for cdn.predix-ui.com will expire on the 27th Feb 2019. 
Chrome is already flagging this up as an issue then requesting fonts.

**Comment by evanjd** [comment]
@ed-the-cat Where are you seeing 27th Feb? I'm seeing March 10th.

<img width="489" alt="screen shot 2019-02-21 at 8 39 58 pm" src="https://user-images.githubusercontent.com/4055224/53158959-f344d400-3618-11e9-89e4-9c346845d4c0.png">

This also lines up with what Netlify sees:
<img width="528" alt="screen shot 2019-02-21 at 8 41 52 pm" src="https://user-images.githubusercontent.com/4055224/53159038-25563600-3619-11e9-8e70-da360bf78e52.png">

**Comment by ed-the-cat** [comment]
When I attempt to open the font location directly in Chrome, it reports

![image](https://user-images.githubusercontent.com/17332871/53159346-9c5de100-35bd-11e9-841c-abfc060cb811.png)

**Comment by evanjd** [comment]
The issuer on that cert is not what's installed on cdn.predix-ui.com. Our certs are issued by Lets Encrypt, not GE External Issuing CA.

MyApps effectively performs a MITM attack against all traffic when you're connected to their proxy. My guess is that it's MyApps certs that are used for intercepting SSL traffic that are the problem, _not_ cdn.predix-ui.com. Do you notice SSL errors on other sites too?

**Comment by ed-the-cat** [comment]
Ok - Thank you for looking in to so quickly - I'll follow up at our end - cheers.

**Comment by evanjd** [comment]
No problem!

**Comment by evanjd** [comment]
For what it's worth, I can confirm that I also see GE's injected cert when connecting to cdn.predix-ui.com via zscaler/MyApps:

<img width="492" alt="screen shot 2019-02-21 at 9 05 45 pm" src="https://user-images.githubusercontent.com/4055224/53160715-9e0ac180-361c-11e9-9d9c-e3d6b95cfad9.png">

No SSL errors though. In your case, GE is specifying the wrong subject in the cert (`*.netlify.com`, when it should be `*.predix-ui.com`). For whatever reason that doesn't happen to me.
